// Mock hotel data in the Philippines
export interface Hotel {
  id: string;
  name: string;
  description: string;
  location: string;
  price: number;
  rating: number;
  reviews: number;
  image: string;
  amenities: string[];
  availability: number;
  hourlyCostRange?: { min: number; max: number };
}

export const MOCK_HOTELS: Hotel[] = [
  {
    id: "hotel-1",
    name: "Luxury Ocean View Resort",
    description: "Experience breathtaking ocean views",
    location: "Boracay, Aklan",
    price: 450,
    rating: 4.8,
    reviews: 324,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Gym", "Restaurant", "Spa", "Beach Access"],
    availability: 5,
    hourlyCostRange: { min: 60, max: 120 },
  },
  {
    id: "hotel-2",
    name: "Downtown Modern Hotel",
    description: "Contemporary luxury in the heart of the city",
    location: "Makati City, Metro Manila",
    price: 320,
    rating: 4.6,
    reviews: 512,
    image: "https://images.unsplash.com/photo-1595909352763-b798883426dd?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Gym", "Restaurant", "Business Center", "Concierge"],
    availability: 8,
    hourlyCostRange: { min: 45, max: 90 },
  },
  {
    id: "hotel-3",
    name: "Cozy Mountain Retreat",
    description: "Perfect mountain getaway with stunning views",
    location: "Baguio City, Benguet",
    price: 280,
    rating: 4.7,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1551632786-de41ec28a16b?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Fireplace", "Mountain Bike", "Hiking", "Hot Tub"],
    availability: 3,
    hourlyCostRange: { min: 35, max: 75 },
  },
  {
    id: "hotel-4",
    name: "Tropical Paradise Resort",
    description: "Island living at its finest with pristine beaches",
    location: "El Nido, Palawan",
    price: 520,
    rating: 4.9,
    reviews: 401,
    image: "https://images.unsplash.com/photo-1566650885640-65e3a54b9eb8?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Beach", "Water Sports", "Spa", "Bar"],
    availability: 2,
    hourlyCostRange: { min: 80, max: 150 },
  },
  {
    id: "hotel-5",
    name: "Historic Boutique Hotel",
    description: "Charming historic hotel with old-world elegance",
    location: "Vigan, Ilocos Sur",
    price: 380,
    rating: 4.5,
    reviews: 276,
    image: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Restaurant", "Concierge", "Library", "Cultural Tours"],
    availability: 6,
    hourlyCostRange: { min: 55, max: 110 },
  },
  {
    id: "hotel-6",
    name: "Desert Luxury Oasis",
    description: "Modern luxury meets serene surroundings",
    location: "Cebu City, Cebu",
    price: 400,
    rating: 4.7,
    reviews: 298,
    image: "https://images.unsplash.com/photo-1561599810-10cb3c94f357?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Golf Course", "Spa", "Restaurant"],
    availability: 7,
    hourlyCostRange: { min: 50, max: 100 },
  },
  {
    id: "hotel-7",
    name: "Waterfront Luxury Hotel",
    description: "Relax and enjoy seaside luxury",
    location: "Subic Bay, Zambales",
    price: 360,
    rating: 4.6,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1576675783962-0ed432c8fa0d?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Restaurant", "Bar", "Gym"],
    availability: 5,
  },
  {
    id: "hotel-8",
    name: "City Center Elegance Hotel",
    description: "Modern luxury in the heart of the city",
    location: "Iloilo City, Iloilo",
    price: 310,
    rating: 4.5,
    reviews: 198,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Gym", "Restaurant", "Concierge", "Business Center"],
    availability: 4,
  },
  {
    id: "hotel-9",
    name: "Mountain View Lodge",
    description: "Serene mountain retreat for relaxation",
    location: "Sagada, Mountain Province",
    price: 250,
    rating: 4.7,
    reviews: 123,
    image: "https://images.unsplash.com/photo-1501117716987-c8e3f3f0b216?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Hiking", "Fireplace", "Hot Tub"],
    availability: 3,
  },
  {
    id: "hotel-10",
    name: "Island Adventure Resort",
    description: "Adventure and luxury on a private island",
    location: "Coron, Palawan",
    price: 480,
    rating: 4.9,
    reviews: 342,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Diving", "Spa", "Bar", "Water Sports"],
    availability: 2,
  },
  {
    id: "hotel-11",
    name: "Siargao Surf Resort",
    description: "Perfect spot for surfing and island life",
    location: "Siargao, Surigao del Norte",
    price: 420,
    rating: 4.8,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1598887142480-9aa460fa4be1?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Surfing", "Bar", "Restaurant"],
    availability: 3,
  },
  {
    id: "hotel-12",
    name: "Bohol Riverside Hotel",
    description: "Relax by the river with modern comfort",
    location: "Tagbilaran, Bohol",
    price: 300,
    rating: 4.6,
    reviews: 225,
    image: "https://images.unsplash.com/photo-1573153944268-7c9f4261a2fb?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Restaurant", "Spa", "Gym"],
    availability: 6,
  },
  {
    id: "hotel-13",
    name: "Tagaytay Sky Resort",
    description: "Cool mountain air and stunning views",
    location: "Tagaytay, Cavite",
    price: 350,
    rating: 4.7,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Restaurant", "Spa", "Bar"],
    availability: 4,
  },
  {
    id: "hotel-14",
    name: "Palawan Beachfront Villa",
    description: "Private villa with exclusive beachfront access",
    location: "Puerto Princesa, Palawan",
    price: 500,
    rating: 4.9,
    reviews: 398,
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Private Beach", "Spa", "Restaurant"],
    availability: 2,
  },
  {
    id: "hotel-15",
    name: "Cebu Island Resort",
    description: "Luxury resort on a tropical island",
    location: "Mactan Island, Cebu",
    price: 470,
    rating: 4.8,
    reviews: 360,
    image: "https://images.unsplash.com/photo-1501117716987-c8e3f3f0b216?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Diving", "Bar", "Restaurant", "Spa"],
    availability: 5,
  },
  {
    id: "hotel-16",
    name: "Davao Rainforest Retreat",
    description: "Escape to the rainforest with luxury amenities",
    location: "Davao City, Davao del Sur",
    price: 340,
    rating: 4.6,
    reviews: 190,
    image: "https://images.unsplash.com/photo-1551907234-6e3c9638d5b6?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Hiking", "Pool", "Spa", "Restaurant"],
    availability: 4,
  },
  {
    id: "hotel-17",
    name: "Vigan Heritage Hotel",
    description: "Step back in time in this heritage hotel",
    location: "Vigan, Ilocos Sur",
    price: 320,
    rating: 4.5,
    reviews: 160,
    image: "https://images.unsplash.com/photo-1598887142480-9aa460fa4be1?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Restaurant", "Library", "Cultural Tours"],
    availability: 5,
  },
  {
    id: "hotel-18",
    name: "Subic Bay Marina Hotel",
    description: "Luxury by the marina with stunning sunset views",
    location: "Subic Bay, Zambales",
    price: 380,
    rating: 4.7,
    reviews: 220,
    image: "https://images.unsplash.com/photo-1561599810-10cb3c94f357?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Bar", "Restaurant", "Gym"],
    availability: 4,
  },
  {
    id: "hotel-19",
    name: "Iloilo Riverside Suites",
    description: "Modern suites by the riverside",
    location: "Iloilo City, Iloilo",
    price: 310,
    rating: 4.5,
    reviews: 180,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Gym", "Restaurant", "Concierge"],
    availability: 6,
  },
  {
    id: "hotel-20",
    name: "Siargao Luxury Beach Resort",
    description: "Relax and enjoy the best beach on the island",
    location: "Siargao, Surigao del Norte",
    price: 460,
    rating: 4.9,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1598887142480-9aa460fa4be1?w=500&h=400&fit=crop",
    amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Beach Access"],
    availability: 3,
  },
];
